name: gudang_fk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  printing: ^5.14.2
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5

  # Excel + Barcode GAMBAR
  syncfusion_flutter_xlsio: ^31.2.12
  barcode_image: ^2.0.3
  image: ^4.5.4
  universal_html: ^2.3.0

  # Barcode untuk UI (widget)
  barcode: ^2.2.4
  barcode_widget: ^2.0.4

  # Lain-lain yang tadinya salah tempat
  flutter_svg: ^2.0.9
  get: ^4.6.5
  shared_preferences: ^2.2.2
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/rumah.png"
